"""Emit three tables into the Supplementary Information.

The main text carries no tables, so the confidence bounds, the summed-envelope
map and the secondary records appear in the supplement or nowhere.  Generated
from the results files, never retyped.
"""
from __future__ import annotations

import pathlib

import numpy as np
import pandas as pd

import masses as M

F0 = M.offset_F0("C")
# The manuscript tree is not part of the public package; fall back to results/
# so the tables are still reproducible from the shipped code and data.
_MS = pathlib.Path("../manuscript/si")
OUT = str(_MS / "si_extra_tables.tex") if _MS.is_dir() else "../results/si_extra_tables.tex"
L = []

b = pd.read_csv("../results/bounds_uncertainty.csv")
import bounds_uncertainty as _bu
_WORD = {5: "five", 72: "seventy-two", 64: "sixty-four"}


def _sci(x, nd=0):
    e = int(np.floor(np.log10(abs(x))))
    m = x / 10 ** e
    return (f"$10^{{{e}}}$" if nd == 0 and abs(m - 1) < 1e-9
            else f"${m:.{nd}f}\\times10^{{{e}}}$")
_top = b[b.rho == 0.0].sort_values("point", ascending=False).head(4)
# the header below says "all ecDHFR"; fail rather than mislabel if that changes
assert set(_top.family) == {"ecDHFR"}, f"top series now include {set(_top.family)}"
top = _top.variant.tolist()
L += [r"\begin{table}[!htbp]",
      r"\caption{One-sided $95\%$ lower confidence bounds on the offset for the "
      r"four series with the highest point estimates, bracketed over the unknown "
      r"correlation $\rho$ between the H/T and D/T effects induced by the shared "
      r"tritium reference. The threshold for excluding the ground-channel model "
      r"is $\Fz=-0.0421$; no entry reaches it. Each bound is on the series "
      r"maximum of the endpoint: the one-sided bound for each temperature at "
      r"level $0.05/n_T$, then the largest of these, which has coverage at least "
      r"$95\%$ by the union bound. Bounds average " + _WORD[_bu.N_REP] +
      r" replications of " + _sci(_bu.N_DRAW) + r" draws; the largest Monte Carlo "
      r"standard deviation over all " + _WORD[4 * len(b) // 4] + r" cells is " +
      _sci(b.lcb_mc_sd.max(), 1) + r". The bracket includes $\rho=-1$, the "
      r"maximally adverse case.}",
      r"\label{tab:unc-si}", r"\begin{center}\small",
      r"\begin{tabular}{lccccc}", r"\toprule",
      r"Series (all ecDHFR) & point & $\rho=-1$ & $\rho=0$ & $\rho=0.5$ & $\rho=0.9$\\",
      r"\midrule"]
for v in top:
    s = b[b.variant == v]
    L.append(f"{v} & ${s[s.rho==0].point.iloc[0]:.4f}$ & "
             f"${s[s.rho==-1.0].lcb.iloc[0]:.3f}$ & "
             f"${s[s.rho==0].lcb.iloc[0]:.3f}$ & ${s[s.rho==0.5].lcb.iloc[0]:.3f}$ & "
             f"${s[s.rho==0.9].lcb.iloc[0]:.3f}$\\\\")
L += [r"\bottomrule", r"\end{tabular}", r"\end{center}", r"\end{table}", ""]

# The summed-vibronic table (tab:bvib-si) was withdrawn together with its data.
# Its grid maxima sat at the upper edge of the A range in 27 of 32 cells and
# reverse sign when that range is extended, so the entries were wrong in sign
# rather than merely uncertain.  See the SI section "The summed vibronic
# envelope is permissive".

s = pd.read_csv("../data/secondary_adh.csv")
s["gamma_obs"] = np.log(s.K_HT) / np.log(s.K_DT)
s = s.sort_values("gamma_obs", ascending=False)
L += [r"\begin{table}[!htbp]",
      r"\caption{Observed secondary competitive effects for alcohol "
      r"dehydrogenase, tabulated for reference only. "
      r"$\gamma^{\mathrm{obs}}=\ln\KHT/\ln\KDT$ reproduces the published "
      r"exponent to $0.05$ in every case. These measurements come from the "
      r"mixed-labeling design, in which the H/T effect accompanies C--H cleavage "
      r"and the D/T effect accompanies C--D cleavage, so the two ratios are "
      r"referred to different molecules and do not share a commitment. "
      r"Theorem~1 of the main text does not apply to them, and we draw no "
      r"identification inference from these values in either direction.}",
      r"\label{tab:sec-si}", r"\begin{center}\small",
      r"\begin{tabular}{llcccc}", r"\toprule",
      r"Enzyme & Form & $\KHT$ & $\KDT$ & $\gamma^{\mathrm{obs}}$ & published\\",
      r"\midrule"]
for _, r in s.iterrows():
    L.append(f"{r.family} & {r.variant} & "
             f"${r.K_HT:.3f}\\pm{r.K_HT_se:.3f}$ & ${r.K_DT:.3f}\\pm{r.K_DT_se:.3f}$ & "
             f"${r.gamma_obs:.2f}$ & ${r.exp_pub}\\pm{r.exp_pub_se}$\\\\")
L += [r"\bottomrule", r"\end{tabular}", r"\end{center}", r"\end{table}", ""]

open(OUT, "w").write("% Generated by export_si_tables.py -- do not edit.\n"
                     + "\n".join(L) + "\n")
print(f"wrote {OUT}: 2 tables, {len(top)} bound rows, {len(s)} secondary rows")
