"""Emit the three tables that live in the REVTeX main text into the PNAS SI.

The PNAS main text has no tables (6-page limit), so the confidence bounds, the
summed-envelope map and the secondary records must appear in the SI or they
appear nowhere.  Generated from the results files, never retyped.
"""
from __future__ import annotations

import pathlib

import numpy as np
import pandas as pd

import masses as M

F0 = M.offset_F0("C")
# The manuscript tree is not part of the public package; fall back to results/
# so the tables are still reproducible from the shipped code and data.
_MS = pathlib.Path("../manuscript/si")
OUT = str(_MS / "si_extra_tables.tex") if _MS.is_dir() else "../results/si_extra_tables.tex"
L = []

b = pd.read_csv("../results/bounds_uncertainty.csv")
top = b[b.rho == 0.0].sort_values("point", ascending=False).head(4).variant.tolist()
L += [r"\begin{table}[!htbp]",
      r"\caption{One-sided $95\%$ lower confidence bounds on the offset for the "
      r"four series with the highest point estimates, bracketed over the unknown "
      r"correlation $\rho$ between the H/T and D/T effects induced by the shared "
      r"tritium reference. The threshold for excluding the ground-channel model "
      r"is $\Fz=-0.0421$; no entry reaches it. Bounds are simultaneous over the "
      r"temperatures of a series and averaged over five replications of "
      r"$5\times10^{4}$ draws; the largest Monte Carlo standard deviation over "
      r"all sixty-four cells is $7.4\times10^{-4}$. The bracket includes "
      r"$\rho=-1$, the maximally adverse case.}",
      r"\label{tab:unc-si}", r"\begin{center}\small",
      r"\begin{tabular}{lccccc}", r"\toprule",
      r"Series (all ecDHFR) & point & $\rho=-1$ & $\rho=0$ & $\rho=0.5$ & $\rho=0.9$\\",
      r"\midrule"]
for v in top:
    s = b[b.variant == v]
    L.append(f"{v} & ${s[s.rho==0].point.iloc[0]:.4f}$ & "
             f"${s[s.rho==-1.0].lcb.iloc[0]:.4f}$ & "
             f"${s[s.rho==0].lcb.iloc[0]:.4f}$ & ${s[s.rho==0.5].lcb.iloc[0]:.4f}$ & "
             f"${s[s.rho==0.9].lcb.iloc[0]:.4f}$\\\\")
L += [r"\bottomrule", r"\end{tabular}", r"\end{center}", r"\end{table}", ""]

# The summed-vibronic table (tab:bvib-si) was withdrawn together with its data.
# Its grid maxima sat at the upper edge of the A range in 27 of 32 cells and
# reverse sign when that range is extended, so the entries were wrong in sign
# rather than merely uncertain.  See the SI section "The summed vibronic
# envelope is permissive".

s = pd.read_csv("../data/secondary_adh.csv")
s["gamma_obs"] = np.log(s.K_HT) / np.log(s.K_DT)
s = s.sort_values("gamma_obs", ascending=False)
L += [r"\begin{table}[!htbp]",
      r"\caption{Observed secondary competitive effects for alcohol "
      r"dehydrogenase, tabulated for reference only. "
      r"$\gamma^{\mathrm{obs}}=\ln\KHT/\ln\KDT$ reproduces the published "
      r"exponent to $0.05$ in every case. These measurements come from the "
      r"mixed-labeling design, in which the H/T effect accompanies C--H cleavage "
      r"and the D/T effect accompanies C--D cleavage, so the two ratios are "
      r"referred to different molecules and do not share a commitment. "
      r"Theorem~1 of the main text does not apply to them, and we draw no "
      r"identification inference from these values in either direction.}",
      r"\label{tab:sec-si}", r"\begin{center}\small",
      r"\begin{tabular}{llcccc}", r"\toprule",
      r"Enzyme & Form & $\KHT$ & $\KDT$ & $\gamma^{\mathrm{obs}}$ & published\\",
      r"\midrule"]
for _, r in s.iterrows():
    L.append(f"{r.family} & {r.variant} & "
             f"${r.K_HT:.3f}\\pm{r.K_HT_se:.3f}$ & ${r.K_DT:.3f}\\pm{r.K_DT_se:.3f}$ & "
             f"${r.gamma_obs:.2f}$ & ${r.exp_pub}\\pm{r.exp_pub_se}$\\\\")
L += [r"\bottomrule", r"\end{tabular}", r"\end{center}", r"\end{table}", ""]

open(OUT, "w").write("% Generated by export_si_tables.py -- do not edit.\n"
                     + "\n".join(L) + "\n")
print(f"wrote {OUT}: 2 tables, {len(top)} bound rows, {len(s)} secondary rows")
