"""Data for the asymmetry figure: primary identified sets against the two
thresholds.  The secondary panel was removed: the mixed-labeling design does not
satisfy the shared-commitment condition, so no inference is drawn from it."""
from __future__ import annotations

import numpy as np
import pandas as pd

import masses as M
from partial_id import F_min_exact

GSC = M.gamma_sc("C"); F0 = M.offset_F0("C")
OUT = "../figures/tikz/data/"

# ---- panel (a): primary identified sets, one row per series / enzyme form
rows = []
RHO = -1.0            # maximally adverse; every bound drawn is the worst case


def _lcb(point, kht, kht_se, kdt, kdt_se, rho=RHO):
    """One-sided 95% lower bound on the offset at correlation `rho`."""
    sH, sD = kht_se/kht, kdt_se/kdt
    sd = np.sqrt(sH**2 + (GSC*sD)**2 - 2*GSC*rho*sH*sD)
    return point - 1.645*sd

_TB = pd.read_csv("../data/trinomial_benchmark.csv")
_FAM = {"FDH": "formate dehydrogenase", "TSase": "thymidylate synthase",
        "ecDHFR": "Escherichia coli dihydrofolate reductase",
        "hsDHFR": "Homo sapiens dihydrofolate reductase",
        "MAOB": "monoamine oxidase"}


def _series_closed(r):
    """Is the plotted endpoint of this series attained at finite commitment?

    A series row plots the largest endpoint over its temperatures, so whether
    that endpoint is attained is a property of the single record achieving it.
    The identified set is closed exactly when L_H < gamma; otherwise the
    endpoint is approached only as the commitment diverges and is excluded.
    """
    sub = _TB[_TB.system.str.contains(_FAM.get(r.family, r.family), case=False,
                                      na=False)
              & (_TB.variant.astype(str) == str(r.variant))]
    if r.family == "TSase" and "step" in _TB.columns:
        sub = sub[sub.step.astype(str) == str(r.step)]
    vals = [F_min_exact(x.K_HT, x.K_DT) for _, x in sub.iterrows()
            if x.K_HT > x.K_DT > 1]
    if not vals:
        raise ValueError(f"no benchmark record for {r.family} {r.variant}")
    best = max(vals, key=lambda v: v[0])
    if abs(best[0] - r.point) > 1e-6:
        raise ValueError(f"endpoint mismatch for {r.family} {r.variant}: "
                         f"{r.point} vs {best[0]}")
    return bool(best[3])


b = pd.read_csv("../results/bounds_uncertainty.csv")
# Conservative throughout: every bound is the maximally adverse rho = -1 case,
# so any system drawn as clearing F0 clears it under any correlation.
b = b[b.rho == RHO]
# TSase contributes both a hydride- and a proton-transfer series; without the
# step in the label the two WT rows are indistinguishable in the figure.
multi = {f for f, g in b.groupby("family") if g.step.nunique() > 1}
for _, r in b.iterrows():
    lab = f"{r.family} {r.variant}"
    if r.family in multi:
        lab += f" ({r.step})"
    rows.append((lab, r.point, r.lcb, "series", _series_closed(r)))
lad = pd.read_csv("../data/ladh_adh_primary.csv")
# A form measured by two studies at different temperatures is two analysis
# units, as the two amine oxidase pH values already are; the temperature
# disambiguates the label only where a form appears more than once.
_dup = {v for v, g in lad.groupby("variant") if len(g) > 1}
for _, r in lad.iterrows():
    f, _, _, cl = F_min_exact(r.K_HT, r.K_DT)
    lab = f"LADH {r.variant}"
    if r.variant in _dup:
        lab += f" {int(r.T_C)}$^\\circ$C"
    rows.append((lab, f,
                 _lcb(f, r.K_HT, r.K_HT_se, r.K_DT, r.K_DT_se), "ladh", cl))
bs = pd.read_csv("../data/bsao_grant1989.csv")
for _, r in bs.iterrows():
    f, _, _, cl = F_min_exact(r.K_HT, r.K_DT)
    rows.append((f"BSAO {r.variant}", f,
                 _lcb(f, r.K_HT, r.K_HT_se, r.K_DT, r.K_DT_se), "bsao", cl))
ya = pd.read_csv("../data/cha1989_yadh.csv")
a = ya[ya.note.str.contains("average")].iloc[0]
f, _, _, cl = F_min_exact(a.K_HT, a.K_DT)
rows.append(("YADH wild type", f,
             _lcb(f, a.K_HT, a.K_HT_se, a.K_DT, a.K_DT_se), "yadh", cl))

df = pd.DataFrame(rows, columns=["label", "point", "lcb", "grp", "closed"])
df = df.sort_values("point").reset_index(drop=True)
df["y"] = np.arange(len(df)) + 1
inf_mask = df.lcb > F0

# ---- single-column panel.  The full endpoint range spans 1.0 log units but the
# comparison is decided within 0.05 of F0, so the axis is cut at XMIN and the two
# systems below it are marked off-scale with their endpoints printed in the row
# label.  At this scale |F0| spans ~3.5 mm, so no magnified inset is needed.
XMIN, XMAX = -0.50, 0.20
RAY = 0.050                      # short ray: the set is open above
off = df[df.point < XMIN]
with open(OUT + "fa_rays.tex", "w") as fh:
    fh.write("% generated by export_fig_asym.py -- do not edit\n")
    for _, r in df.iterrows():
        col  = "cPro" if r.lcb > F0 else "cGrey"
        wcol = "cPro!45" if r.lcb > F0 else "cGrey!40"
        lw = "0.9pt" if r.lcb > F0 else "0.6pt"
        start = max(r.point, XMIN)
        fh.write(f"\\draw[{col}, line width={lw}, -{{Straight Barb[length=1.9pt,"
                 f"width=2.8pt]}}] (axis cs:{start:.5f},{r.y}) -- "
                 f"(axis cs:{start+RAY:.5f},{r.y});\n")
        if r.point >= XMIN:
            fh.write(f"\\draw[{wcol}, line width={lw}] "
                     f"(axis cs:{max(r.lcb,XMIN):.5f},{r.y}) -- "
                     f"(axis cs:{r.point:.5f},{r.y});\n")
            # filled when the endpoint is attained at finite commitment,
            # open when it is only approached, which the caption relies on
            if r.closed:
                fh.write(f"\\fill[{col}] (axis cs:{r.point:.5f},{r.y}) "
                         f"circle (0.85pt);\n")
            else:
                fh.write(f"\\draw[{col}, line width=0.45pt, fill=white] "
                         f"(axis cs:{r.point:.5f},{r.y}) circle (0.95pt);\n")
        else:
            # endpoint lies off the left edge: chevron instead of a dot
            fh.write(f"\\node[font=\\fontsize{{6.2}}{{7.4}}\\selectfont, color={col}, "
                     f"anchor=east, inner sep=0.6pt] at (axis cs:{XMIN:.5f},{r.y}) "
                     f"{{$\\ll$}};\n")
        lab = r.label if r.point >= XMIN else f"{r.label} ({r.point:.2f})"
        # off-scale rows carry a chevron at XMIN, so their labels sit further
        # left to keep clear of it
        dx = 0.032 if r.point >= XMIN else 0.060
        fh.write(f"\\node[rowlab] at (axis cs:{XMIN-dx:.5f},{r.y}) {{{lab}}};\n")
print(f"panel: {len(df)} rows, {len(off)} off-scale below {XMIN}")
for _, r in off.iterrows():
    print(f"   off-scale: {r.label} at {r.point:+.4f}")

print(f"panel: {int(inf_mask.sum())} informative of {len(df)}")
print(f"panel: {int(df.closed.sum())} closed endpoints, "
      f"{int((~df.closed).sum())} open")
