"""Regenerate manuscript/sm_table_bounds.tex from results/modelfree_bounds.csv.

The table shipped for a long time with a header claiming it came from
export_si_tables.py, which never wrote it: nothing regenerated it, so it drifted
whenever the benchmark changed.  It is generated here instead, from the same
file the text quotes.
"""
from __future__ import annotations

import pathlib

import pandas as pd

import masses as M
from corpus import display_family

F0 = M.offset_F0("C")
# Always results/.  Until 2026-09-14 this wrote into a manuscript directory
# outside the repository whenever that directory existed, including one kept
# only as an archived record, which a generator must never edit.
OUT = pathlib.Path("../results/sm_table_bounds.tex")

d = pd.read_csv("../results/modelfree_bounds.csv").sort_values(
    "bound", ascending=False)

lines = ["% Generated by analysis/export_bounds_table.py -- do not edit; "
         "edit the generator.\n"]
for _, r in d.iterrows():
    lines.append(f"{display_family(r.family, r.variant)} & {r.variant} & {r.step} & {int(r.n_T)} & "
                 f"{r.bound:.4f} & {abs(r.bound - F0):.4f} & {abs(r.bound):.4f} & "
                 f"{'yes' if r.any_interior else 'no'}\\\\\n")
OUT.write_text("".join(lines))
print(f"[written] {OUT}  ({len(d)} series)")
