"""Data for the asymmetry figure: identified sets against the two thresholds."""
from __future__ import annotations

import numpy as np
import pandas as pd

import masses as M
from partial_id import F_min_exact

GSC = M.gamma_sc("C"); F0 = M.offset_F0("C")
OUT = "../figures/tikz/data/"

# ---- panel (a): primary identified sets, one row per series / enzyme form
rows = []
b = pd.read_csv("../results/bounds_uncertainty.csv")
b = b[b.rho == 0.0]
for _, r in b.iterrows():
    rows.append((f"{r.family} {r.variant}", r.point, r.lcb, "series"))
lad = pd.read_csv("../data/ladh_adh_primary.csv")
for _, r in lad.iterrows():
    f, _, _, _ = F_min_exact(r.K_HT, r.K_DT)
    sd = np.sqrt((r.K_HT_se/r.K_HT)**2 + (GSC*r.K_DT_se/r.K_DT)**2)
    rows.append((f"LADH {r.variant}", f, f - 1.645*sd, "ladh"))
ya = pd.read_csv("../data/cha1989_yadh.csv")
a = ya[ya.note.str.contains("average")].iloc[0]
f, _, _, _ = F_min_exact(a.K_HT, a.K_DT)
sd = np.sqrt((a.K_HT_se/a.K_HT)**2 + (GSC*a.K_DT_se/a.K_DT)**2)
rows.append(("YADH wild type", f, f - 1.645*sd, "yadh"))

df = pd.DataFrame(rows, columns=["label", "point", "lcb", "grp"])
df = df.sort_values("point").reset_index(drop=True)
df["y"] = np.arange(len(df)) + 1
inf_mask = df.lcb > F0
RAY = 0.085                      # short ray: the set is open above
with open(OUT + "fa_rays.tex", "w") as fh:
    fh.write("% generated by export_fig_asym.py -- do not edit\n")
    for _, r in df.iterrows():
        col  = "cPro" if r.lcb > F0 else "cGrey"
        wcol = "cPro!45" if r.lcb > F0 else "cGrey!40"
        lw = "0.9pt" if r.lcb > F0 else "0.6pt"
        fh.write(f"\\draw[{col}, line width={lw}, -{{Straight Barb[length=1.9pt,"
                 f"width=2.8pt]}}] (axis cs:{r.point:.5f},{r.y}) -- "
                 f"(axis cs:{r.point+RAY:.5f},{r.y});\n")
        fh.write(f"\\draw[{wcol}, line width={lw}] "
                 f"(axis cs:{r.lcb:.5f},{r.y}) -- (axis cs:{r.point:.5f},{r.y});\n")
        fh.write(f"\\fill[{col}] (axis cs:{r.point:.5f},{r.y}) circle (1.05pt);\n")
        fh.write(f"\\node[rowlab] at (axis cs:-1.02,{r.y}) {{{r.label}}};\n")

# zoomed inset: the records that come closest to the thresholds
zoom = df[df.point > -0.20].copy().reset_index(drop=True)
zoom["yz"] = np.arange(len(zoom)) + 1
RAYZ = 0.012
with open(OUT + "fa_zoom.tex", "w") as fh:
    fh.write("% generated by export_fig_asym.py -- do not edit\n")
    for _, r in zoom.iterrows():
        col  = "cPro" if r.lcb > F0 else "cGrey"
        wcol = "cPro!45" if r.lcb > F0 else "cGrey!40"
        fh.write(f"\\draw[{col}, line width=0.7pt, -{{Straight Barb[length=1.7pt,"
                 f"width=2.5pt]}}] (axis cs:{r.point:.5f},{r.yz}) -- "
                 f"(axis cs:{r.point+RAYZ:.5f},{r.yz});\n")
        fh.write(f"\\draw[{wcol}, line width=0.7pt] "
                 f"(axis cs:{r.lcb:.5f},{r.yz}) -- (axis cs:{r.point:.5f},{r.yz});\n")
        fh.write(f"\\fill[{col}] (axis cs:{r.point:.5f},{r.yz}) circle (0.9pt);\n")
print(f"inset: {len(zoom)} rows, x from {zoom.lcb.min():.3f} to "
      f"{zoom.point.max()+RAYZ:.3f}")
print(f"panel a: {len(df)} rows, {int(inf_mask.sum())} informative, "
      f"y range 1..{len(df)}")

# ---- panel (b): secondary, largest excludable reference
s = pd.read_csv("../results/secondary_adh.csv").sort_values("gamma_lcb")
s = s.reset_index(drop=True); s["y"] = np.arange(len(s)) + 1
with open(OUT + "fb_sec.dat", "w") as fh:
    fh.write("y gobs lcb hi\n")
    for _, r in s.iterrows():
        fh.write(f"{r.y} {r.gamma_obs:.4f} {r.gamma_lcb:.4f} "
                 f"{r.gamma_obs + 1.645*r.gamma_se:.4f}\n")
with open(OUT + "fb_labels.dat", "w") as fh:
    fh.write("y label\n")
    for _, r in s.iterrows():
        fh.write(f"{r.y} {{{r.family} {r.variant}}}\n")
print(f"panel b: {len(s)} rows; robust vs 4.8: {int(s.robust_48.sum())}")
print(f"  F0 = {F0:.6f}   gamma_SC = {GSC:.5f}")

# ---- zoomed inset for panel (a): the records nearest the thresholds
zoom = df[df.point > -0.20].copy().reset_index(drop=True)
zoom["yz"] = np.arange(len(zoom)) + 1
RAYZ = 0.012
with open(OUT + "fa_zoom.tex", "w") as fh:
    fh.write("% generated by export_fig_asym.py -- do not edit\n")
    for _, r in zoom.iterrows():
        col = "cPro" if r.lcb > F0 else "cGrey"
        wcol = "cPro!45" if r.lcb > F0 else "cGrey!40"
        fh.write(f"\\draw[{col}, line width=0.7pt, -{{Straight Barb"
                 f"[length=1.7pt,width=2.5pt]}}] (axis cs:{r.point:.5f},{r.yz})"
                 f" -- (axis cs:{r.point + RAYZ:.5f},{r.yz});\n")
        fh.write(f"\\draw[{wcol}, line width=0.7pt] (axis cs:{r.lcb:.5f},"
                 f"{r.yz}) -- (axis cs:{r.point:.5f},{r.yz});\n")
        fh.write(f"\\fill[{col}] (axis cs:{r.point:.5f},{r.yz}) circle (0.9pt);\n")
print(f"inset: {len(zoom)} rows, x {zoom.lcb.min():.3f} to "
      f"{zoom.point.max() + RAYZ:.3f}")
